export enum Opcode {
  HALT = 0x00,
  PUSH = 0x01,
  PUSHI = 0x02,
  PAIR = 0x03,
  UNPAIR = 0x04,
  HASH = 0x05,
  DUP = 0x06,
  SWAP = 0x07,
  DROP = 0x08,
  LOAD = 0x09,
  STORE = 0x0a,
  ADD = 0x0b,
  EQ = 0x0c,
  JUMP = 0x0d,
  JZ = 0x0e,
  JNZ = 0x0f,
  OVER = 0x10,
  ROT = 0x11,
  CALL = 0x12,
  RET = 0x13,
}

export const OPCODE_NAMES: Record<number, string> = {
  [Opcode.HALT]: "HALT",
  [Opcode.PUSH]: "PUSH",
  [Opcode.PUSHI]: "PUSHI",
  [Opcode.PAIR]: "PAIR",
  [Opcode.UNPAIR]: "UNPAIR",
  [Opcode.HASH]: "HASH",
  [Opcode.DUP]: "DUP",
  [Opcode.SWAP]: "SWAP",
  [Opcode.DROP]: "DROP",
  [Opcode.LOAD]: "LOAD",
  [Opcode.STORE]: "STORE",
  [Opcode.ADD]: "ADD",
  [Opcode.EQ]: "EQ",
  [Opcode.JUMP]: "JUMP",
  [Opcode.JZ]: "JZ",
  [Opcode.JNZ]: "JNZ",
  [Opcode.OVER]: "OVER",
  [Opcode.ROT]: "ROT",
  [Opcode.CALL]: "CALL",
  [Opcode.RET]: "RET",
};
