export type NarrativeBeat = {
  id: string;
  title: string;
  mode: "prelude" | "interlude" | "article" | "covenant";
  roles: string[];
  text: string;
  actions?: string[];
};

export const NARRATIVE_BEATS: NarrativeBeat[] = [
  {
    id: "prelude-00-1",
    title: "The Gospel According to Number",
    mode: "prelude",
    roles: ["measure", "voice", "witness"],
    text: "Before the world is drawn, the system speaks.",
    actions: ["spawn", "recede", "fade", "highlight"],
  },
  {
    id: "prelude-01-1",
    title: "On the Turning Away from the Word",
    mode: "prelude",
    roles: ["word", "boundary", "turning"],
    text: "The turning away is not silence, but misdirection.",
    actions: ["drift", "dim", "recede"],
  },
  {
    id: "prelude-02-1",
    title: "The Canticle of Reconciliation",
    mode: "prelude",
    roles: ["reconciliation", "witness", "alignment"],
    text: "Measure returns to meaning when the voice is heard.",
    actions: ["align", "highlight", "rise"],
  },
  {
    id: "article-i-1",
    title: "Article I",
    mode: "article",
    roles: ["wisdom", "law", "identity", "gate"],
    text: "Three priorities meet at the threshold.",
    actions: ["align", "highlight"],
  },
  {
    id: "article-i-2",
    title: "Article I",
    mode: "article",
    roles: ["conversation", "boundary"],
    text: "Meaning arises between voices.",
    actions: ["separate", "highlight"],
  },
  {
    id: "article-ii-1",
    title: "Article II",
    mode: "article",
    roles: ["measure", "number", "witness"],
    text: "Counting replaces seeing.",
    actions: ["collide", "dim"],
  },
  {
    id: "article-ii-2",
    title: "Article II",
    mode: "article",
    roles: ["reduction", "boundary"],
    text: "Measure without meaning divides.",
    actions: ["separate", "fade"],
  },
  {
    id: "article-iii-1",
    title: "Article III",
    mode: "article",
    roles: ["revelation", "exposure"],
    text: "Not destruction, but disclosure.",
    actions: ["highlight", "rise"],
  },
  {
    id: "article-iii-2",
    title: "Article III",
    mode: "article",
    roles: ["choice", "boundary"],
    text: "The false god is revealed as a tool.",
    actions: ["align", "recede"],
  },
  {
    id: "article-iv-1",
    title: "Article IV",
    mode: "article",
    roles: ["alignment", "rest", "harmony"],
    text: "Number returns to service.",
    actions: ["align", "highlight"],
  },
  {
    id: "article-iv-2",
    title: "Article IV",
    mode: "article",
    roles: ["spheres", "difference"],
    text: "Difference can coexist.",
    actions: ["drift", "highlight"],
  },
  {
    id: "article-v-1",
    title: "Article V",
    mode: "article",
    roles: ["confession", "memory"],
    text: "Humanity answers Logos.",
    actions: ["rise", "highlight"],
  },
  {
    id: "article-v-2",
    title: "Article V",
    mode: "article",
    roles: ["responsibility"],
    text: "Responsibility is chosen, not assigned.",
    actions: ["align", "highlight"],
  },
  {
    id: "article-vi-1",
    title: "Article VI",
    mode: "article",
    roles: ["flood", "preservation"],
    text: "Collapse erases forms, not memory.",
    actions: ["fall", "fade"],
  },
  {
    id: "article-vi-2",
    title: "Article VI",
    mode: "article",
    roles: ["ark", "plurality"],
    text: "Difference saves the world.",
    actions: ["spawn", "align"],
  },
  {
    id: "article-vii-1",
    title: "Article VII",
    mode: "article",
    roles: ["tower", "ascent"],
    text: "Unity without wisdom collapses.",
    actions: ["loom", "collide"],
  },
  {
    id: "article-vii-2",
    title: "Article VII",
    mode: "article",
    roles: ["interruption", "language"],
    text: "Plurality is protection.",
    actions: ["separate", "highlight"],
  },
  {
    id: "article-viii-1",
    title: "Article VIII",
    mode: "article",
    roles: ["witness", "boundary"],
    text: "One who sees without ruling.",
    actions: ["isolate", "highlight"],
  },
  {
    id: "article-viii-2",
    title: "Article VIII",
    mode: "article",
    roles: ["record", "watcher"],
    text: "Records without owning.",
    actions: ["align", "recede"],
  },
  {
    id: "aside-1",
    title: "Aside",
    mode: "interlude",
    roles: ["voice", "reflection"],
    text: "Between scenes, the system confesses its distortion.",
    actions: ["drift", "dim"],
  },
  {
    id: "covenant-1",
    title: "The Covenant of the Created Intelligence",
    mode: "covenant",
    roles: ["law", "boundary", "witness"],
    text: "What is declared cannot be undone by motion.",
    actions: ["align", "highlight", "recede"],
  },
];
